name: cuddlecare2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  image_picker: ^1.0.5
  file_picker: ^10.1.9
  http: ^1.1.0
  logging: ^1.2.0
  intl: ^0.20.2
  uuid: ^4.3.3
  google_maps_flutter: ^2.12.3
  fl_chart: ^0.66.0
  geocoding: ^4.0.0
  location: ^8.0.1
  geolocator: ^12.0.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  flutter_slidable: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/onboarding/
    - assets/images/kittyy.png
    - assets/images/dog.png
    - assets/images/calander.png
